# version: 'version' not required

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - my_mongo_data:/data/db

  # Node service
  api:
    build: . # Looks for the Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

    environment:
      # Database Configuration
      DB_HOST: mongo_db
      DB_PORT: 27017
      DB_NAME: myurlshortener
    depends_on:
      - mongo_db

volumes:
  my_mongo_data: {}
